[project]
name = "cryptic-validation-engine"
authors = []
description = ""
telemetry = true
requirements = []
cache_dir = "/home/runner/workspace/cryptic-validation-engine/./.requirements"
boot_contracts = ["pox", "costs-v2", "bns"]
[contracts.cryptic-validation-engine]
path = "contracts/cryptic-validation-engine.clar"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
